export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const START_LOADING_LOGIN = 'START_LOADING_LOGIN'
export const END_LOADING_LOGIN = 'END_LOADING_LOGIN'