export const GET_ALL_CULINARIES = 'GET_ALL_CULINARIES'
export const START_LOADING_ALL_CULINARIES = 'START_LOADING_ALL_CULINARIES'
export const END_LOADING_ALL_CULINARIES = 'END_LOADING_ALL_CULINARIES'
