export const LOAD_SINGLE_BANNER = 'LOAD_SINGLE_BANNER'
export const START_LOADING_SINGLE_BANNER = 'START_LOADING_SINGLE_BANNER'
export const ERROR_LOADING_SINGLE_BANNER = 'ERROR_LOADING_SINGLE_BANNER'
export const NOT_FOUND_SINGLE_BANNER = 'NOT_FOUND_SINGLE_BANNER'